#!/bin/sh

printf '\x1b[1mcargo fmt\x1b[m\n'
if cargo fmt &> /dev/null; then
  printf '\x1b[1mcargo\x1b[m\n'
  if cargo build --color always --release; then
    echo SUCCESS
    exit 0
  else
    echo error: cargo build failed
  fi
else
  if cargo build --color always --release; then
    cargo --color always fmt -- --color always
    echo error: cargo fmt failed
  else
    echo error: cargo build failed
  fi
fi
exit 1

