[package]
name = "lobby"
default-run = "lobby"
version = "0.1.0"
authors = ["ma27"]
edition = "2021"
description = "The game-lobby."

[dependencies]
rocket = "0.4.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dependencies.rocket_contrib]
version = "0.4.4"
default-features = false
features = ["json"]
